[[constraint]]
	name = "github.com/urfave/cli"
	version = "1.20.0"

[[constraint]]
	name = "github.com/storozhukBM/verifier"
	branch = "master"

[[constraint]]
	name = "github.com/emersion/go-smtp"
	branch = "master"

[[constraint]]
	name = "github.com/emersion/go-sasl"
	branch = "master"

[[constraint]]
	name = "golang.org/x/sync"
	branch = "master"

[[constraint]]
	name = "golang.org/x/text"
	branch = "master"

[[constraint]]
	name = "github.com/phalaaxx/milter"
	branch = "master"

[[constraint]]
	name = "github.com/h2non/filetype"
	branch = "master"

[[constraint]]
	name = "golang.org/x/net"
	branch = "master"

[[constraint]]
	name = "github.com/jdkato/prose"
	branch = "v2"

[[constraint]]
	name = "github.com/abadojack/whatlanggo"
	branch = "master"

[[constraint]]
	name = "github.com/kljensen/snowball"
	version = "0.6.0"

[[constraint]]
	name = "github.com/mvdan/xurls"
	version = "2.0.0"

[[constraint]]
    name = "github.com/inconshreveable/log15"
	branch = "master"

[[constraint]]
	name = "github.com/prometheus/client_golang"
	version = "0.9.x"

[[constraint]]
    name = "github.com/go-redis/redis"
    version = "6.14.2"

[[constraint]]
    name = "github.com/go-gomail/gomail"
    branch = "v2"

[[constraint]]
    name = "github.com/go-cmd/cmd"
    version = "1.0.4"

[[constraint]]
    name = "github.com/mostlygeek/go-exiftool"
    branch = "master"

[[constraint]]
    name = "github.com/nwaples/rardecode"
    branch = "master"

[[constraint]]
    name = "github.com/oklog/ulid"
    version = "1.3.1"

[[constraint]]
    name = "github.com/fsnotify/fsnotify"
    version = "1.4.7"

[[constraint]]
    name = "github.com/tinylib/msgp"
    branch = "master"

[[constraint]]
    name = "github.com/pierrec/lz4"
    version = "2.0.7"

[[constraint]]
    name = "github.com/xi2/xz"
    branch = "master"

[[constraint]]
    name = "github.com/gabriel-vasile/mimetype"
    branch = "master"

[[constraint]]
    name = "github.com/schollz/pake"
    version = "1.1.0"

[[constraint]]
    name = "github.com/awnumar/memguard"
    version = "0.15.0"

[[constraint]]
    name = "github.com/uber-go/atomic"
    version = "1.3.2"

[[constraint]]
    name = "golang.org/x/crypto"
    branch = "master"

[[constraint]]
    name = "github.com/gin-gonic/gin"
    version = "1.3.0"

[[constraint]]
	name = "github.com/DavidBelicza/TextRank"
	version = "2.1.1"

[[constraint]]
    name = "github.com/blabber/mbox"
    branch = "master"

[[constraint]]
    name = "github.com/rafaeljesus/rabbus"
    version = "2.2.1"

[prune]
	go-tests = true
	unused-packages = true
